# Generated by Django 5.2.4 on 2025-08-02 08:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_donor_name', models.CharField(blank=True, help_text='Name for anonymous donations', max_length=100)),
                ('anonymous_donor_email', models.EmailField(blank=True, help_text='Email for anonymous donations', max_length=254)),
                ('donation_type', models.CharField(choices=[('shelter', 'Shelter Donation'), ('platform', 'Platform Support'), ('emergency', 'Emergency Fund'), ('general', 'General Animal Welfare')], help_text='Type of donation', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment'), ('other', 'Other')], help_text='Payment method used', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', help_text='Current payment status', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External payment processor transaction ID', max_length=100)),
                ('payment_processor', models.CharField(blank=True, help_text='Payment processor used (Stripe, PayPal, etc.)', max_length=50)),
                ('message', models.TextField(blank=True, help_text='Optional message from donor')),
                ('dedication', models.CharField(blank=True, help_text='Dedication or memorial information', max_length=200)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide donor information from public display')),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring donation?')),
                ('recurring_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], help_text='Frequency for recurring donations', max_length=20)),
                ('is_tax_deductible', models.BooleanField(default=True, help_text='Is this donation tax deductible?')),
                ('receipt_sent', models.BooleanField(default=False, help_text='Has receipt been sent to donor?')),
                ('receipt_email', models.EmailField(blank=True, help_text='Email address for receipt', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('donor', models.ForeignKey(blank=True, help_text='User who made the donation (null for anonymous donations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(blank=True, help_text='Shelter receiving the donation (null for platform donations)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='shelters.shelter')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Campaign title', max_length=200)),
                ('description', models.TextField(help_text='Detailed campaign description')),
                ('short_description', models.CharField(help_text='Brief campaign summary', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Campaign image', null=True, upload_to='campaigns/%Y/%m/')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target donation amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current amount raised', max_digits=12)),
                ('start_date', models.DateTimeField(help_text='Campaign start date')),
                ('end_date', models.DateTimeField(help_text='Campaign end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Campaign status', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this campaign on homepage')),
                ('allow_anonymous_donations', models.BooleanField(default=True, help_text='Allow anonymous donations to this campaign')),
                ('total_donors', models.PositiveIntegerField(default=0, help_text='Total number of donors')),
                ('average_donation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average donation amount', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created the campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(blank=True, help_text='Shelter benefiting from campaign (null for platform campaigns)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='shelters.shelter')),
            ],
            options={
                'verbose_name': 'Donation Campaign',
                'verbose_name_plural': 'Donation Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique receipt number', max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('tax_year', models.PositiveIntegerField(help_text='Tax year for this receipt')),
                ('receipt_file', models.FileField(blank=True, help_text='Generated receipt PDF file', null=True, upload_to='receipts/%Y/')),
                ('email_sent', models.BooleanField(default=False, help_text='Has receipt been emailed?')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When receipt was emailed', null=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Donation Receipt',
                'verbose_name_plural': 'Donation Receipts',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_type', '-created_at'], name='donations_d_donatio_3bf848_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['shelter', '-created_at'], name='donations_d_shelter_e02185_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_status'], name='donations_d_payment_453297_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', '-created_at'], name='donations_d_donor_i_04ef46_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcampaign',
            index=models.Index(fields=['status', '-start_date'], name='donations_d_status_feba2d_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcampaign',
            index=models.Index(fields=['is_featured', '-created_at'], name='donations_d_is_feat_c3bedf_idx'),
        ),
        migrations.AddIndex(
            model_name='donationcampaign',
            index=models.Index(fields=['shelter', '-created_at'], name='donations_d_shelter_991506_idx'),
        ),
    ]
